version: "3"
services:
  api:
    image: valanm/fastapi
    depends_on:
      - postgres
    ports:
      - "80:8000"
    # volumes:
    #   - ./:/usr/src/app:ro
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_USER=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
